.MODEL SMALL
.STACK 100H
.DATA
MSG1   DB 'ENTER A NUMBER: $'
MSG2   DB 'THE NUMBER IS POSITIVE AND EVEN.$'
MSG3   DB 'THE NUMBER IS POSITIVE AND ODD.$'
MSG4   DB 'THE NUMBER IS NEGATIVE AND EVEN.$'
MSG5   DB 'THE NUMBER IS NEGATIVE AND ODD.$'
NUM    DB 0

.CODE
MAIN PROC
    MOV  AX, DATA
    MOV  DS, AX            ; INITIALIZE DATA SEGMENT

    MOV  AH, 9
    LEA  DX, MSG1          ; PROMPT USER
    INT  21H

    MOV  AH, 1
    INT  21H
    SUB  AL, 30H           ; CONVERT ASCII TO NUMERIC

    MOV  BL, AL
    ROL  AL, 15            ; ROTATE LEFT THROUGH CARRY
    SAR  AL, 7             ; EXTRACT SIGN BIT

    CMP  AL, 0
    JG   POSITIVE          ; JUMP IF NUMBER IS POSITIVE
    ; IF NUMBER IS NEGATIVE
    CMP  BL, 1             ; CHECK IF NUMBER IS ODD OR EVEN
    JE   NEG_ODD
    ; PRINT NEGATIVE AND EVEN MESSAGE
    LEA  DX, MSG4
    JMP  OUT

NEG_ODD:
    ; PRINT NEGATIVE AND ODD MESSAGE
    LEA  DX, MSG5
    JMP  OUT

POSITIVE:
    ; IF NUMBER IS POSITIVE
    CMP  BL, 1             ; CHECK IF NUMBER IS ODD OR EVEN
    JE   POS_ODD
    ; PRINT POSITIVE AND EVEN MESSAGE
    LEA  DX, MSG2
    JMP  OUT

POS_ODD:
    ; PRINT POSITIVE AND ODD MESSAGE
    LEA  DX, MSG3

OUT:
    MOV  AH, 9
    INT  21H

    MOV  AH, 4CH
    INT  21H               ; TERMINATE PROGRAM
    MAIN ENDP
END MAIN
